const ACTIONS = {
  BROWSER: {
    REGISTER_EVENT_SUCCESS: 'REGISTER_EVENT_SUCCESS',
    UNREGISTER_EVENT_SUCCESS: 'UNREGISTER_EVENT_SUCCESS',
    UPDATE_VIEWPORT_SIZE: 'UPDATE_VIEWPORT_SIZE',
  },
  SEARCH: {
    SEARCH_STARTED: 'SEARCH_STARTED',
    SEARCH_RESULT_SUCCESS: 'SEARCH_RESULT_SUCCESS',
    SEARCH_RESULT_FAILURE: 'SEARCH_RESULT_FAILURE',
    SEARCH_PARTIAL_RESULT_SUCCESS: 'SEARCH_PARTIAL_RESULT_SUCCESS',
  },
};

export default ACTIONS;
