const ACTIONS = {
  BROWSER: {
    REGISTER_EVENT_SUCCESS: 'REGISTER_EVENT_SUCCESS',
    UNREGISTER_EVENT_SUCCESS: 'UNREGISTER_EVENT_SUCCESS',
    MEASURE_RENDERED_ELEMENT_SUCCESS: 'MEASURE_RENDERED_ELEMENT_SUCCESS',
    MEASURE_RENDERED_ELEMENT_FAILURE: 'MEASURE_RENDERED_ELEMENT_FAILURE',
  },
  SEARCH: {
    SEARCH_STARTED: 'SEARCH_STARTED',
    SEARCH_RESULT_SUCCESS: 'SEARCH_RESULT_SUCCESS',
    SEARCH_RESULT_FAILURE: 'SEARCH_RESULT_FAILURE',
    SEARCH_PARTIAL_RESULT_SUCCESS: 'SEARCH_PARTIAL_RESULT_SUCCESS',
  },
};

export default ACTIONS;
